# Generated by Django 3.1 on 2020-08-15 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200814_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='helptable',
            name='amount2',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
